#!/bin/bash

[ "$#" -eq 0 ] && set -- "-"

for ARG in "$@"
do
	CURSOR="$ARG"
	[ -z "$CURSOR" ] && CURSOR="$(pwd)"
	[ "$CURSOR" = "-" ] && CURSOR="$(pwd)"

	[ -d "$CURSOR" ] && echo $CURSOR
	while true
	do
		CURSOR="$(dirname $CURSOR)"
		[[ "$CURSOR" = "/" || "$CURSOR" = "." ]]  && break
		echo $CURSOR
	done
done
